### ISSUE TITLE
Rename the expected_exception option

### ISSUE THREAD

**Issue by xabbuh** [sensiolabs-de/rich-model-forms-bundle#49]
The current name of the `expected_exception` option is misleading. It can easily be misinterpreted as the developer expecting the model to *always*  throw these exceptions given the behaviour one observes in PHPUnit when using `@expectedException` and the like.

Talking to other people on the conferences we talked about this bundle we got some good suggestions for a better name. Amongst these are the following (I probably forgot some):

- `intercept_exception`
- `catch_exception`
- `validation_exception`
- `handle_exception`
- `throws`
- `catch`

**Comment by xosofox** [comment]
Maybe, if you explain again here what the consequence of this option is, we might get a better understanding of what the naming should indicate

**Comment by xabbuh** [comment]
What this option does is the following: You give it a list of exception classes that may be thrown by your domain model when the data is written from the form to your model. These exceptions will then be caught and do not bubble up. Instead they will be handled by the `GenericExceptionHandler` which will attach a `FormError` to the form based on the exception message.

**Comment by tobiassjosten** [comment]
I suggested `catch` on Twitter but with this list I think `handle_exception` is an even better suggestion. It describes very accurately what it would do.

**Comment by chr-hertel** [comment]
i would like to move away from exception specific terminology. right now we're just supporting exceptions, but there are way more advanced pattern of dealing with invalide state:
e.g. https://martinfowler.com/articles/replaceThrowWithNotification.html

IMO we should focus on the fact that we are converting domain specific errors to form errors.
might be quite hard to tackle all in one, but we should think about different concepts of `error_strategy` and i guess the ExceptionHandler extension point is a pretty good start

**Comment by chr-hertel** [comment]
it might be quite impossible to handle all different strategies of error handling in user domain so we need to come up with an very simple extension point to solve that issue

my best idea so far
```php
$builder
    ->add('fieldName', FieldType::class, [
        'errors' => [
            Error::byException('price_error', [PriceException::class])
                ->withMessage('form_error.translation_key')
                ->withTranslationDomain('form_errors'),
        ],
    ]);
```

with

```php
class Error
{
    public static function byException(string $name, string|string[] $expectedTypes = null): self { ... }
}
```

**Comment by xabbuh** [comment]
pull request waiting for review at #55
