### ISSUE TITLE
Attempts to map SubmitType to model

### ISSUE THREAD

**Issue by dbrumann** [sensiolabs-de/rich-model-forms-bundle#57]
When adding a SubmitType to a FormType the bundle attempts to map it to the model.

## Reproducer example:

https://github.com/dbrumann/rich-form-bug1/pull/1

## How to reproduce

1. Build a form mapping a model with a SubmitType

2. Build a controller for processing the form and a template using `{{ form(form) }}` for rendering the form

3. Open the page and submit the form

=> The form throws an error because the submit cannot be mapped to the object

**Comment by chr-hertel** [comment]
if i'm getting it right, the issue is that we're trying to fetch view data from the [Submit]ButtonType
we could filter for that in `SensioLabs\RichModelForms\DataTransformer\ValueObjectTransformer`

but i don't why this is happening
