### ISSUE TITLE
Factory closure to work as callable

### ISSUE THREAD

**Issue by zmitic** [sensiolabs-de/rich-model-forms-bundle#61]
Right now, using callable for factory is like this (I removed options for brevity):

```php
public function buildForm(FormBuilderInterface $builder, array $options): void
{
    $builder->add('campaign', EntityType::class);       
    $builder->add('invoicedToClient', DateType::class);
}

public function configureOptions(OptionsResolver $resolver): void
{
    $resolver->setDefaults([
        'factory' => [$this, 'factory'],
    ]);
}

public function factory(Campaign $campaign, DateTime $invoicedToClient): Invoice
{
    return new Invoice($campaign, $invoicedToClient);
}
```

The signature of ``factory()`` method must match names of form fields which helps in finding errors. 

Typehinting parameters will also help static analysis tools; example is if user adds new dependency to Invoice::__construct() method, these tools will find issue in this ``InvoiceType`` form. 

Example:

```php
class Invoice
{
	public function __construct(Campaign $x, DateTime $y, bool $c)
	{...}
}
```

Unlike callables, [closures](https://github.com/sensiolabs-de/rich-model-forms-bundle/blob/master/docs/factory_value_object.md#initializing-objects)  will receive form data as array.

So creating instance of Invoice would prevent static analysis:

```php
'factory' => function (array $data) {
    return new Invoice($data['campaign', $data['invoicedToClient'])
}
```

---

My suggestion is to change this decision and allow Closures to work the same as callables. If accepted, above example would be:

```php
'factory' => function (Campaign $campaign, DateTime $invoicedToClient) {
	return new Invoice($campaign, $invoicedToClient);
},
```

Another big advantage is that this way, we could use form normalizers and construct data object in different way, based on some other option.

So if param ``$c`` is supposed to be injected from controller, normalizer would be this:

```php
public function configureOptions(OptionsResolver $resolver): void
{
    $resolver->setRequired('some_param');
 	$resolver->setNormalizer('factory', function (Options $options) {
		$someParam = $options['some_param'];

		return function ($campaign, $invoicedToClient) use ($someParam) {
			return new Invoice($campaign, $invoicedToClient, $someParam);
		}

		// or with upcoming arrow functions:
		// return fn($campaign, $invoicedToClient) => new Invoice($campaign, $invoicedToClient, $someParam);
	})
}

```

With callables, we cannot use normalizers because other options cannot be passed to it.

**Comment by hjkl** [comment]
I'd like to see this as well, supplying a closure should work in the same way as other callables for consistency as well as all the advantages detailed by zmitic 👍

**Comment by xabbuh** [comment]
I think this change makes sense and we should be able to make the BC break in 0.3.0.
