### ISSUE TITLE
Validation errors on embeddable form submission

### ISSUE THREAD

**Issue by mykbas** [sensiolabs-de/rich-model-forms-bundle#91]
Tried to rewrite example with SF5+`rich-model-forms-bundle v.0.6.0`  https://github.com/sensiolabs-de/rich-model-forms-demo
Trying to submit ProductType with embeddable PriceType throws an error `This value should be of type App\Entity\Price.`.
Everything seems to be correct, Category form works well with similar settings.
Maybe I'm doing smth wrong?

ProductType.php
```
->add('price', PriceType::class, [
    'read_property_path' => 'getPrice',
    'write_property_path' => 'costs',
    'handle_exception' => PriceException::class,
]);
```
Entity/Product.php
```php
public function getPrice(): Price
{
    return $this->price;
}
public function costs(Price $price): void
{
    $this->price = $price;
}
```

PriceType
```php
class PriceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('amount', MoneyType::class, [
                'divisor' => 100,
            ])
            ->add('tax', PercentType::class, [
                'type' => 'integer',
            ])
            ->add('currency', CurrencyType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefault('factory', Price::class);
        $resolver->setDefault('immutable', true);
    }
}
```

**Comment by xabbuh** [comment]
Can you create small example application that allows to reproduce this?

**Comment by mykbas** [comment]
@xabbuh of course, please the code here https://github.com/mykbas/fich-model-forms

**Comment by mykbas** [comment]
@xabbuh thank you for the help, now it works!

**Comment by xabbuh** [comment]
@mykbas I also added a comment to the PR with some explanation.
